FROM mielune/alpine-python3-arm
MAINTAINER Martin <Munsio> Treml

WORKDIR /app
COPY ./src/configurator.py ./run.sh /app/
RUN chmod a+x ./configurator.py ./run.sh

# Default listening port.
EXPOSE 8123

# The configuration yaml for persistance.
VOLUME /config

ENTRYPOINT ["/app/run.sh"]
